colours = ("Red", "Green", "Blue")
print(colours)
print(colours[0])
print(colours[2])

months = ("January", "February", "March", "April")
print(months)
print(months[0])
print(months[1])
print(months[2])
print(months[3])
print(months[-1])
print(months[-2])
print(months[-3])
